[package]
name = "schnorr_sigma_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4.4" , features = ["rand"] }
rand = "0.8.5"
primes = "0.3.0"